name: Deploy Project to the Server

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:

          - ip: HOST1
            node: "22.x"

          - ip: HOST2
            node: "22.x"
            
    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
        
      - name: Prepare .env file
        run: echo "NEXT_PUBLIC_GIT_HASH=${{ github.head_ref }}.${{ github.sha }}" > .env.production

      - name: Install Node modules
        run: pnpm install

      - name: Generate Prisma client
        run: pnpm prisma generate

      - name: Build TypeScript for ${{ matrix.domain }}
        run: pnpm build

      - name: Deploy to Hetzner server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete -q"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST1 }}
          REMOTE_USER: "meotimdihia"
          # The new deployment is named "project3"
          TARGET: "/home/meotimdihia/sources/project3/"
          EXCLUDE: ".env"

      - name: Restart project service via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST1 }}
          username: meotimdihia
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart project@3001 project@3003 project@3005 project@3007
